server:
  port: 40001
logging:
  config: classpath:log4j-test.xml
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.11.96:3306/yesway-project-framework-monolith?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: devmysqlu
    password: DEV95&&mysql
    hikari:
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为，默认值：true
      pool-name: HikariConnectionPool
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟)
      max-lifetime: 1800000 #控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
      connection-timeout: 10000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    cluster:
      nodes: 10.1.11.16:6379,10.1.11.17:6379,10.1.11.18:6379,10.1.11.16:6479,10.1.11.17:6479,10.1.11.18:6479
    lettuce:
      pool:
        max-active: 10
        max-wait: 3000ms
        min-idle: 0
        max-idle: 10
    timeout: 5000
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  mail:
    host: smtp.qq.com
    username: 100103081@qq.com
    password: ltsjolgvxshibiii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
yesway:
  http:
    cors:
      mapping: "/**"
      headers: "*"
      origins: "*"
      methods: "*"
      age: 7200
      credentials: true
    security:
      signin: /signin
      signout: /signout
      ignore-urls:
        - /v1/users/v1/forget-password/exists
        - /v1/users/v1/forget-password/send
        - /v1/users/v1/forget-password/update
        - /v1/users/v1/forget-password/need-verify
        - /v1/jigsaw-verify/v1/create
        - /v1/jigsaw-verify/v1/validate
  cpsp:
    account: YCloud
    service: EgpbbcGvjT
    security: PLC4BpRiZU
    gateway: http://cpsptest.yesway.cn/ycpsp-gateway
    token-url: http://cpsptest.yesway.cn/ycpsp-gateway/api/token
    send-sms-url: http://cpsptest.yesway.cn/ycpsp-gateway/sms/sendtext